
export type Post = {
  pfp: string,
  name: string,
  username: string,
  title: string,
  text: string,
  media: string,
  numOfComments: number,
  numOfReposts: number,
  upvotes: number,
  downvotes: number
}

export type ProfilePic = {
    id: "Dwu85P9SOIk",
    created_at: "2016-05-03T11:00:28-04:00",
    updated_at: "2016-07-10T11:00:01-05:00",
    width: 2448,
    height: 3264,
    color: "#6E633A",
    blur_hash: "LFC$yHwc8^$yIAS$%M%00KxukYIp",
    downloads: 1345,
    likes: 24,
    liked_by_user: false,
    description: "A man drinking a coffee.",
    exif: {
      make: "Canon",
      model: "Canon EOS 40D",
      exposure_time: "0.011111111111111112",
      aperture: "4.970854",
      focal_length: "37",
      iso: 100
    },
    location: {
      name: "Montreal, Canada",
      city: "Montreal",
      country: "Canada",
      position: {
        latitude: 45.473298,
        longitude: -73.638488
      }
    },
    current_user_collections: [ // The *current user's* collections that this photo belongs to.
      {
        id: 206,
        title: "Makers: Cat and Ben",
        published_at: "2016-01-12T18:16:09-05:00",
        last_collected_at: "2016-06-02T13:10:03-04:00",
        updated_at: "2016-07-10T11:00:01-05:00",
        cover_photo: null,
        user: null
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d",
      full: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg",
      regular: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=1080&fit=max",
      small: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=400&fit=max",
      thumb: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=200&fit=max"
    },
    links: {
      self: "https://api.unsplash.com/photos/Dwu85P9SOIk",
      html: "https://unsplash.com/photos/Dwu85P9SOIk",
      download: "https://unsplash.com/photos/Dwu85P9SOIk/download"
      download_location: "https://api.unsplash.com/photos/Dwu85P9SOIk/download"
    },
    user: {
      id: "QPxL2MGqfrw",
      updated_at: "2016-07-10T11:00:01-05:00",
      username: "exampleuser",
      name: "Joe Example",
      portfolio_url: "https://example.com/",
      bio: "Just an everyday Joe",
      location: "Montreal",
      total_likes: 5,
      total_photos: 10,
      total_collections: 13,
      instagram_username: "instantgrammer",
      twitter_username: "crew",
      links: {
        self: "https://api.unsplash.com/users/exampleuser",
        html: "https://unsplash.com/exampleuser",
        photos: "https://api.unsplash.com/users/exampleuser/photos",
        likes: "https://api.unsplash.com/users/exampleuser/likes",
        portfolio: "https://api.unsplash.com/users/exampleuser/portfolio"
      }
    }
  }

export type RedditResponseObject = {
  data: Data,
  kind: string
}

type Data = {
  approved_at_utc: null,
subreddit: string,
selftext: string,
author_fullname: string,
saved: boolean,
mod_reason_title: null,
gilded: number,
clicked: boolean,
title: string,
  link_flair_richtext: null,
subreddit_name_prefixed: string,
hidden: boolean,
pwls: number,
link_flair_css_class: string,
downs: number,
thumbnail_height: number,
top_awarded_type: null,
hide_score: boolean,
name: string,
quarantine: boolean,
link_flair_text_color: string,
upvote_ratio: number,
author_flair_background_color: null,
subreddit_type: string,
ups: number,
total_awards_received: string,
media_embed: null,
thumbnail_width: number,
author_flair_template_id: null,
is_original_content: boolean,
user_reports: null,
secure_media: null,
is_reddit_media_domain: boolean,
is_meta: boolean,
category: null,
secure_media_embed: null,
link_flair_text: string,
  can_mod_post: boolean,
score: number,
approved_by: null,
is_created_from_ads_ui: boolean,
author_premium: boolean,
thumbnail: string,
edited: boolean,
author_flair_css_class: null,
author_flair_richtext: null,
gildings: {
gid_1: number,
},
post_hint: string,
content_categories: null,
is_self: boolean,
mod_note: null,
created: number,
link_flair_type: string,
wls: number,
removed_by_category: null,
banned_by: null,
author_flair_type: string,
domain: string,
allow_live_comments: boolean,
selftext_html: null,
likes: null,
suggested_sort: null,
banned_at_utc: null,
url_overridden_by_dest: string,
view_count: null,
archived: boolean,
no_follow: boolean,
is_crosspostable: boolean,
pinned: boolean,
over_18: boolean,
preview: null,
all_awardings: null,
awarders: null,
media_only: boolean,
can_gild: boolean,
spoiler: boolean,
locked: boolean,
author_flair_text: null,
treatment_tags: null,
visited: boolean,
removed_by: null,
num_reports: null,
distinguished: null,
subreddit_id: string,
author_is_blocked: boolean,
mod_reason_by: null,
removal_reason: null,
link_flair_background_color: string,
  id: string,
is_robot_indexable: boolean,
report_reasons: null,
author: string,
discussion_type: null,
num_comments: number,
send_replies: boolean,
whitelist_status: string,
contest_mode: boolean,
mod_reports: null,
author_patreon_flair: boolean,
author_flair_text_color: null,
permalink: string,
parent_whitelist_status: string,
stickied: boolean,
url: string,
subreddit_subscribers: number,
created_utc: number,
num_crossposts: number,
media: null,
is_video: boolean
}